baseurl = "https://www.peter-doherty.com"
title = "Peter Doherty"

theme = "hugo-coder"

languagecode = "en"

paginate = 100
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "disqus_JWtiMBTuT0"
googleAnalytics = "UA-127743889-1"

[params]
    author = "Peter Doherty"
    description = "Peter Doherty is an Entrepreneur and Chartered Mechanical Engineer with over ten years' experience. He is passionate about developing new businesses and helping existing business grow"
    keywords = "blog,developer,personal,entrepreneur,engineer,bootstrapping,business,ideas,b2b,growth,lean,startup,value,digitalisation,energy,tech,django,vue,python,startup,digital,transformation,entrepreneurship,project,management,design,"
    info = "Entrepreneur · Chartered Engineer · Management & Technical Consulting Services · Software"
    avatarurl = "../images/peterdoherty.jpg"
    # footercontent = "Enter a text here."

    dateformat = "January 2, 2006"

    hideCredits = false
    hideCopyright = false

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Use inverted colors
    inverted = false

    # Custom CSS
    custom_css = []


[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/peter_j_doherty/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/petedoherty/"
[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/peter-doherty/"
[[params.social]]
    name = "angellist"
    icon = "fab fa-angellist"
    weight = 1
    url = "https://angel.co/peter_j_doherty/"
[[params.social]]
    name = "Medium"
    icon = "fab fa-medium"
    weight = 5
    url = "https://medium.com/@peterdoh"
[[params.social]]
    name = "Strava"
    icon = "fab fa-strava"
    weight = 5
    url = "https://www.strava.com/athletes/peterdoh"

# Menu links
[[menu.main]]
    name = "Posts"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "Projects"
    weight = 2
    url = "/projects/"
[[menu.main]]
    name = "Talks"
    weight = 3
    url = "/talks/"
[[menu.main]]
    name = "Reading List"
    weight = 4
    url = "/reading/"
[[menu.main]]
    name = "About"
    weight = 5
    url = "/about/"
[[menu.main]]
    name = "Get In Touch"
    weight = 6
    url = "/get-in-touch/"