baseURL = "http://jenniferdoherty.net/"
languageCode = "en-us"
title = "Jennifer Doherty | Journalist"
theme = "mero"
url = "/categories/"
[params]
  author = "Jennifer Doherty"
  description = "Jennifer Doherty is an NYC based Journalist reporting on Social Justice and Global Poverty."

[menu]
  [[menu.main]]
    identifier = "home"
    name = "About"
    title = "home"
    url = "/"
    weight = 100

  [[menu.main]]
    identifier = "posts"
    name = "Portfolio"
    title = "posts"
    url = "/posts/"
    weight = 200
  
[params.introduction]
   text = "Jennifer Doherty is a Journalist reporting on Social Justice and Global Poverty. Hailing from New Orleans, she obtained a triple major in English, French and International Development. She spent several years living in Paris where she worked for the Organization of Economic & Cooperative Development (OECD) and the Nuclear Energy Agency (NEA) - a division of the OECD. In May 2019, she will graduate with a Masters Degrees in Journalism from Columbia University. She lives in NYC with her husband and dog."

[params.social]
  [[params.social.list]]
  class = "fab"
  icon = "fa-envelope-o"
  url = "mailto:jennifer.doherty@columbia.edu" 

  [[params.social.list]]
  class = "fab"
  icon = "fa-linkedin-in"
  url = "www.linkedin.com/in/jenniekdoh"

  [[params.social.list]]
  class = "fab"
  icon = "fa-twitter"
  url = "www.twitter.com/jennie_k_doh"

  [[params.social.list]]
  class = "fab"
  icon = "fa-instagram"
  url = "www.linkedin.com/in/jenniekdoh"  

[params.footer]
  message = "&copy; 2019 Jennifer Doherty. All rights reserved."
